<?php
// @author: C.A.D. BONDJE DOUE
// @file: winui/stepstate.phtml
// @desc: view winui/stepstate
// @date: 20221224 15:08:34
use IGK\System\Html\Dom\HtmlNode;

$t  || ($t = igk_create_node("div"));
class HtmlStepStateNode extends HtmlNode
{
    var $tagname = "div";
    protected function initialize()
    {
        parent::initialize();
        $this["class"] = "steper";
    }
    public function addStep(string $step)
    {
        $s = igk_create_node("div");
        $s["data-label"] = $step;
        $this->add($s);
        return $this;
    }
}
function igk_html_node_stepstate()
{
    $n = new HtmlStepStateNode();
    return $n;
}
$t->div()->stepstate()
    ->addStep("Initialize")
    ->addStep("Add Product")
    ->addStep("update Database");
function reverseArrayQueries(array $arr, array $operations)
{
    foreach ($operations as $operation) {
        list($start, $end) = $operation;
        $subarray = array_slice($arr, $start, $end - $start + 1);
        $subarray = array_reverse($subarray);
        array_splice($arr, $start, $end - $start + 1, $subarray);
    }
    return $arr;
}
function minMovesToTarget(array $tools, string $target, int $startIndex) {
    $n = count($tools);
    $leftMoves = 0;
    $rightMoves = 0;
    if ($n<=0){
      return 0;
    }
    $end = false;
    $i = $startIndex;
    while(true){
      if ($tools[$i] == $target) {
        break;
      }
      $leftMoves++;
      if ($end && ($i == $startIndex)){
        break;
      }
      $i--;
      if (($i <= 0) && !$end){
        $end = true;
        $i = $n - 1;
      }
    }
    if ($leftMoves==$n){
      return 0;
    }
    $end = false;
    $i = $startIndex;
    while(true){
      if ($tools[$i] == $target) {
        break;
      }
      $rightMoves++;
      $i++;
      if ($end && ($i == $startIndex)){
        break;
      }
      if ($i == $n){
        $i = 0;
        $end = true;
      }
    }
    if ($rightMoves==$n){
      return 0;
    }
    return min($leftMoves, $rightMoves);
  }
function findPairs(array $stockProfit, int $target) {
    $pairCount = 0;
    sort($stockProfit);
    $start = 0;
    $end = count($stockProfit) - 1;
    while ($start < $end) {
        $sum = $stockProfit[$start] + $stockProfit[$end];
        if ($sum == $target) {
            $pairCount++;
            $start++;
            $end--;
        }
        elseif ($sum < $target) {
            $start++;
        }
        else {
            $end--;
        }
    }
    return $pairCount;
}
$stockProfit = [5, 7, 9, 13, 11, 6, 6, 3, 3];
$target = 12;
$pairCount = findPairs($stockProfit, $target);
echo "The number of pairs is: $pairCount";
igk_exit();